version: "3.9"
services:
  torqual-ui:
    build: .
    container_name: torqual-ui
    volumes:
      - ./workspace:/workspace
    ports:
      - "6006:6006"
    command: ng run torqual-ui:storybook --host=0.0.0.0
    tty: true
