version: "3.9"
services:
  ui-lib:
    build: .
    container_name: ui-lib
    volumes:
      - ./workspace:/workspace
    ports:
      - "6006:6006"
    command: ng run ui-lib:storybook --host=0.0.0.0
    tty: true
